# Generated by Django 2.0.5 on 2019-01-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugs',
            new_name='slug',
        ),
    ]
